apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-redis2
  namespace: redis
  labels:
    app: redis-pod2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-pod2
  template:
    metadata:
      labels:
        app: redis-pod2
    spec:
      containers:
      - name: redis-pod2
        image: redis:7.0.11-alpine3.18
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "1000m"
            memory: "128Mi"
          limits:
            cpu: "1"
            memory: "512Mi"
        ports:
        - containerPort: 6379
--- 
apiVersion: v1
kind: Service
metadata:
  name: svc-redis2
  namespace: redis
spec:
  type: ClusterIP
  selector:
    app: redis-pod2
  ports:
    - port: 6379
      targetPort: 6379
